version: '3'

services:
  php:
    build: docker/php
    container_name: php_${CONTAINER_NAME}
    ports:
      - ${PORT_FPM}:9000
    environment:
      # If you develop on Mac OSX change this to remote_host=docker.for.mac.localhost
      # If you develop on Linux change this to remote_host=172.17.0.1
      XDEBUG_CONFIG: "remote_host=docker.for.win.localhost idekey=IDE_XDEBUG"
      PHP_IDE_CONFIG: "serverName=docker-server"
    env_file:
      - .env
    volumes:
      - ./:${WORKING_DIR}:rw,cached
    working_dir: ${WORKING_DIR}

  apache:
    build: docker/apache
    container_name: www_${CONTAINER_NAME}
    ports:
      - ${PORT_HTTP}:${PORT_HTTP}
      - ${PORT_HTTPS}:${PORT_HTTPS}
    env_file:
      - .env
    volumes:
      - ./var/log:/var/log/apache2
      - ./docker/apache/conf/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./docker/apache/conf/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ./:${WORKING_DIR}:ro
      - ./docker/apache/conf/server.crt.dist:/usr/local/apache2/conf/server.crt
      - ./docker/apache/conf/server.key.dist:/usr/local/apache2/conf/server.key
      - ./docker/apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php